### PR TITLE
adding Ledger Group

### PR DESCRIPTION
**Pull request by alensiljak**
This used to be the main Ledger forum. Still active

### CODE REVIEW

**Comment by alensiljak** [comment]
Hi, @simonmichael. Not sure what the best place for adding the forums (in this case the Ledger Google Group) is. It is a mailing list as well as the forum at the same time.

**Comment by simonmichael** [comment]
Thanks. Rather than merge this, I have just fixed the "app-specific mail lists" - that now takes you to the same place I belive.

**Comment by alensiljak** [comment]
Sounds good!

**Comment by alensiljak** [comment]
Oh, wait, the Groups link has been lost.

**Comment by simonmichael** [comment]
https://plaintextaccounting.org/#news-discussion > app-specific mail lists > Ledger > Mail list column > https://groups.google.com/g/ledger-cli , isn't that it ?

**Comment by alensiljak** [comment]
oh, ok. I didn't realize that http://list.ledger-cli.org/ redirects there. Thanks!

**Pull request closed without merging**
