### PR TITLE
Github Workflow for building site with pandoc and pushing output to repo

### PR DESCRIPTION
**Pull request by dustinknopoff**
Automatically prioritized over GitHub-actions bot, this will run pandoc and then commit it to the repo. 

Example: https://dustinknopoff.github.io/plaintextaccounting.github.io/

First pass at #18

### CODE REVIEW

**Review by colindean — APPROVED** [review]
Yeah, this looks good. I've wanted to do this eventually and was picking up some skills to do so having gotten my feet wet with GHA during Hacktoberfest and against this week for a work project.

I think this is a great step in the right direction. I'd like eventually to publish to the gh-pages branch to keep master _just_ source.

I'll let @simonmichael merge this though!

**Comment by simonmichael** [comment]
Thanks @colindean. We were discussing this in the #plaintextaccounting chat, I don't know if you saw. I'll try to understand this in full detail and get it merged soonish.

**Comment by simonmichael** [comment]
I'm having a hard time visualising how everything will work out. I'll merge this and tweak if necessary.

This adds a number of new points of failure and attack, such as:
- docker hub
- the pandoc docker image
- github actions
- [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action)
but the benefit/risk ratio seems acceptable.

Thanks @dustinknopoff !

**Comment by colindean** [comment]
I agree, but I've got a lot of things with high attack values at work relying on these, with some mitigations:

We could eliminate Docker Hub by building our own container image released to ghcr.io (GitHub Packages' Docker Registry) based on https://github.com/pandoc/dockerfiles, which is what builds the Docker Hub container. We could also maintain our own fork of that repo, releasing to ghcr.io. We could also fork the deploy action - I've maintained many such scripts over time, enough that I've come to verify once, pin a hash, and move on.

It's probably safe to trust this infra, esp. because the site is basically reliant on GH working anyway!

**Comment by dustinknopoff** [comment]
It also wouldn't be difficult to apt install pandoc instead of using a docker image.

**Comment by colindean** [comment]
Alas, distros are always so far behind.

* Debian has 2.9.2 in [its latest and next][1].
* Fedora has 2.14 in [35][2].
* Alpine doesn't have it as of v3.15 but [pandoc 2.14 is in edge][3].

Latest pandoc is 2.17. I don't think this codebase _needs_ a bleeding edge pandoc, but maybe 2.9.x would be adequate and thereby eliminate some dependencies...?


[1]: https://packages.debian.org/search?keywords=pandoc&searchon=names&suite=stable&section=all
[2]: https://packages.fedoraproject.org/pkgs/pandoc/pandoc/
[3]: https://pkgs.alpinelinux.org/packages?name=pandoc&branch=edge

**Comment by simonmichael** [comment]
After more discussion and brainstorming - on chat, sorry it's easier sometimes - I have switched the site to use Cloudflare Pages instead of Github Pages. Cloudflare has pandoc, making deployment very simple. (I was already using Cloudflare for the domain. CDN, SSL, redirects, etc.) So, closing this PR, but it was instrumental in making this happen (simpler deploy process, no more manual updating and commiting HTML). Thanks @dustinknopoff !

**Pull request closed without merging**
