### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by n4s-linux**
Dear Plain text accounting.

I have launched a full system based on ledger-cli, hledger, vim, tmux, fzf and a lot of home made scripts.

Its a full double entry accounting system and a second markdown-based brain.

I hope it can make it on Your page.

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks for the link. I can't quite read your docs, but I feel the place you've added the link may not be quite right. That list is the apps that implement PTA and make it possible - larger systems built on top of the PTA apps perhaps fit better somewhere below.

**Comment by n4s-linux** [comment]
How about under Utilities, will that be acceptable ?

**Comment by simonmichael** [comment]
Good question. Your app sounds like more than a utility. Does it have a web UI ?

**Comment by n4s-linux** [comment]
It has a functional PHP based webui, but it is not being maintained.
I distribute the software currently as a full Virtualbox OVA appliance.

So its a whole platform with a tmux-menu system, a lot of scripts to generate reports and import data etc.
Backups according to law and so on.

Its a big and complete software suite to primarily do accounting. It will also have invoicing too at some point because it needs to have according to new laws.

**Comment by simonmichael** [comment]
I know "UI, Web" is a bit limiting, but that seems like the best current place for it. Paisa is a reasonably big web app built on PTA, and it'll go there too. When we get more like yours that could be a good time to start a new section, "Larger apps" or something.

**Comment by n4s-linux** [comment]
Allright thanks, should i close this pull request and make a new one?
Maybe an obvious question, but this is my first pull request ever.
Have a nice day.

**Comment by simonmichael** [comment]
Ah! Excellent. If you have enough git experience, a good way is to amend your commit, then force-push (push -f) to this same PR's branch on github. If that's a hassle, just let me know and I'll do it. Thank you @n4s-linux .

**Comment by n4s-linux** [comment]
If You could help me this one time, it will be much appreciated @simonmichael

**Comment by n4s-linux** [comment]
If You could also help make it link to my repo:
The link is: https://plaintextaccounting.org/

Then I thank You so much.

**Comment by simonmichael** [comment]
Done. Congrats on your project, it sounds interesting!

**Pull request merged**
